import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Layer Caker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-white text-slate-950 antialiased">{children}</body>
    </html>
  );
}
